language: cpp
os: linux
compiler: gcc
sudo: require
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - gcc-6

install:
  - sudo apt-add-repository ppa:beineri/opt-qt59-trusty -y
  - sudo apt-add-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update
  - sudo apt-get install build-essential qt59base qt59declarative qt59quickcontrols2 mesa-common-dev libgl1-mesa-dev pkg-config cmake libnotify-dev --fix-missing -y
  - source /opt/qt*/bin/qt*-env.sh
  - export CXX="g++-6" CC="gcc-6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tests
  - ctest
